spring:
  application:
    name: ITHelpdeskTicketing
  datasource:
    url: jdbc:sqlserver://localhost;databaseName=TABEB31;schema=helpdesk;trustServerCertificate=true
    username: sa
    password: password
#    password: ${DB_PASSWORD}
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServerDialect
      naming:
        physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
    show-sql: false
    properties:
      hibernate:
        default_schema: helpdesk
  mail:
    host: smtp.gmail.com
    port: 587
    username: muhammadariferdiansyah77@gmail.com
    password: gtksmayjuxbilssq
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080