# ==========================================
# PROPERTIES KHUSUS EMAIL (MAILTRAP SANBOX)
# ==========================================
spring.mail.host=sandbox.smtp.mailtrap.io
spring.mail.port=2525
spring.mail.username=a5bdf9437f45b8
spring.mail.password=b962f9c199fcf4
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true